# Generated by Django 5.2.5 on 2025-08-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='tc',
            field=models.BooleanField(default=False),
        ),
    ]
