# Generated by Django 5.2.5 on 2025-09-02 05:02

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularUser',
            fields=[
            ],
            options={
                'verbose_name': 'Regular User',
                'verbose_name_plural': 'Regular Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
            managers=[
                ('objects', account.models.RegularUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
            ],
            options={
                'verbose_name': 'Super User',
                'verbose_name_plural': 'Super Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('account.user',),
            managers=[
                ('objects', account.models.SuperUserManager()),
            ],
        ),
    ]
