# Generated by Django 5.2.5 on 2025-08-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_category_updated_at_productimage_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
