# Generated by Django 5.2.5 on 2025-09-02 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_rename_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_create_category', 'User can Create Category'), ('can_remove_category', 'User can remove Category')], 'verbose_name_plural': 'Categories'},
        ),
    ]
